<a href="https://colab.research.google.com/github/Jenifercynthya/Data-Analysis-using-Python/blob/main/numpy_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr) 

[array([1, 2]), array([3, 4]), array([5, 6])]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

nn= np.split(arr, 4)

print(newarr) 

ValueError: array split does not result in an equal division

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2]) 

[1 2]
[3 4]
[5 6]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2]) 



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]
 [11 12]]


In [ ]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 4)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2]
 [3 4]]


[[5 6]
 [7 8]]


[[ 9 10]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[13 14 15]
 [16 17 18]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]


[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]


[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.vsplit(arr, 3)
print("\n")
print(newarr[0])
print("\n")
print(newarr[1])
print("\n")
print(newarr[2])



[[1 2 3]
 [4 5 6]]


[[ 7  8  9]
 [10 11 12]]


[[13 14 15]
 [16 17 18]]
